app/assets/stylesheets/pages/_favourites.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/views/favourites/index.html.erb
app/views/pages/home.html.erb

started with favourites index page, with some little css, and also tidied up landing page photos

customised favorites, with some css, also tidied up landing page banner to work

---

app/controllers/comments_controller.rb
app/controllers/notifications_controller.rb
app/controllers/votes_controller.rb
app/models/comment.rb
app/models/notification.rb
app/models/review.rb
app/models/user.rb
app/models/vote.rb
app/views/comments/create.html.erb
app/views/comments/destroy.html.erb
app/views/notifications/destroy.html.erb
app/views/notifications/index.html.erb
app/views/votes/create.html.erb
app/views/votes/destroy.html.erb
config/routes.rb
db/migrate/20241016123540_create_votes.rb
db/migrate/20241016123832_create_comments.rb
db/migrate/20241016124203_create_notifications.rb
db/schema.rb
test/controllers/comments_controller_test.rb
test/controllers/notifications_controller_test.rb
test/controllers/votes_controller_test.rb
test/models/comment_test.rb
test/models/notification_test.rb
test/models/vote_test.rb

created models and controllers for votes, comments and notifications
set up associations and validations

framework for vote, comment, notification MVC

---

Gemfile
Gemfile.lock
app/controllers/cinemas_controller.rb
app/models/cinema.rb
app/views/pages/home.html.erb

Searchfunctionality done

---

app/assets/stylesheets/components/_bottom_navbar.scss
app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_cinemas.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_show.scss
app/views/cinemas/index.html.erb
app/views/cinemas/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_bottom_navbar.html.erb
app/views/shared/_header.html.erb
app/views/shared/_navbar.html.erb

home page styling

---

.gitignore
app/assets/stylesheets/pages/_edit.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/reviews_controller.rb
app/views/reviews/edit.html.erb
app/views/reviews/new.html.erb

created an edit form + added back btns for both add/edit review pages

edit form created + dotenv-rails

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/controllers/pages_controller.rb
app/javascript/controllers/map_controller.js
app/models/cinema.rb
app/views/pages/_popup.html.erb
app/views/pages/map.html.erb
config/environments/development.rb
config/importmap.rb
config/initializers/geocoder.rb
db/migrate/20241017133746_add_coordinates_to_cinemas.rb
db/schema.rb
db/seeds.rb

Map with mapbox

---

Gemfile
Gemfile.lock
app/assets/stylesheets/pages/_show.scss
app/controllers/cinemas_controller.rb
app/controllers/comments_controller.rb
app/controllers/reviews_controller.rb
app/controllers/votes_controller.rb
app/javascript/controllers/favourite_controller.js
app/javascript/controllers/reset_form_controller.js
app/models/review.rb
app/models/vote.rb
app/views/cinemas/comment-section-show-page
app/views/cinemas/show.html.erb
app/views/comments/_comment.html.erb
app/views/comments/create.html.erb
app/views/comments/create.turbo_stream.erb
app/views/layouts/application.html.erb
config/environments/development.rb
db/seeds.rb

add voting and comments to reviews

---

app/assets/stylesheets/pages/_new.scss
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

styling updates incl. login page

---

app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_profile.scss
app/controllers/comments_controller.rb
app/controllers/pages_controller.rb
app/views/pages/home.html.erb
app/views/pages/profile.html.erb
db/all_cinemas.rb
db/seeds.rb

- reseeded with only london cinemas (23 total)
- added logout link to profile page
- transferred login/logout info (commented out) to profile page

london seeds & more

---

app/controllers/pages_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/map_controller.js
app/models/cinema.rb
app/views/cinemas/index.html.erb
app/views/layouts/application.html.erb
app/views/pages/map.html.erb
config/environments/development.rb

fixed the map

---

Gemfile
Gemfile.lock
app/assets/stylesheets/pages/_show.scss
app/controllers/comments_controller.rb
app/models/comment.rb
app/views/cinemas/show.html.erb
app/views/comments/_comment.html.erb
config/cable.yml
db/migrate/20241021132312_add_solid_cable.rb
db/schema.rb

Review comment update

---

app/assets/stylesheets/pages/_show.scss
app/javascript/controllers/comments_controller.js
app/views/cinemas/show.html.erb

add comments dropdown

---

app/assets/stylesheets/pages/_favourites.scss
app/controllers/favourites_controller.rb
app/javascript/controllers/favourite_controller.js
app/views/favourites/_list.html.erb
app/views/favourites/index.html.erb

still needs css styling for fav page delete icon

edited fav page so that no more refresh, but cinema show page icon sill not able to toggle delete without refresh

---

app/assets/stylesheets/pages/_show.scss
app/controllers/pages_controller.rb
app/models/comment.rb
app/models/vote.rb
app/views/cinemas/show.html.erb
app/views/shared/_bottom_navbar.html.erb
db/seeds.rb

reseeded with better locations and images
fix error to nullify notification fk when removing votes
allow votes on own review
remove upvote/unvote button, replace with up and down arrows

Updated seed file

---

app/assets/stylesheets/pages/_show.scss
app/views/cinemas/show.html.erb
db/seeds.rb

up and down arrows for vote/unvote
all addresses in map now

vote button, fix geocode

---

app/assets/stylesheets/components/_bottom_navbar.scss
app/views/cinemas/_review.html.erb
app/views/shared/_bottom_navbar.html.erb

profile navbar icon now updated to users profile photo

profile icon updates in reviews and bottom navbar profile icon included

---

app/assets/stylesheets/pages/_show.scss
app/views/comments/_comment.html.erb

delete btn removed + review image css

---

app/controllers/comments_controller.rb
app/models/comment.rb
app/views/cinemas/_review.html.erb

comments now add below the comment form with oldest at the bottom

fix live comment order

---

app/assets/stylesheets/pages/_show.scss
app/controllers/comments_controller.rb
app/models/comment.rb
app/views/cinemas/_review.html.erb
app/views/comments/_comment_count.html.erb

all comments below the form
adds comments to the top of the list 
list sorted in date order
comment count updates in real time when you send a comment

Live comment count

---

app/assets/stylesheets/components/_review_card.scss
app/controllers/comments_controller.rb
app/models/comment.rb
app/views/comments/_comment.html.erb
app/views/comments/_comment_deleted.html.erb
app/views/comments/destroy.html.erb

not perfect, but users can delete their comments after posting

add comment deletion

---

app/assets/stylesheets/components/_bottom_navbar.scss
app/views/shared/_bottom_navbar.html.erb

active tab icon is bright red now and other ones darker

show active tab on navbar

---

app/assets/stylesheets/components/_review_card.scss
app/javascript/controllers/comments_controller.js
app/models/cinema.rb
app/models/review.rb
app/views/cinemas/_review.html.erb
app/views/cinemas/old_comment_format

implement comment modal instead of toggle dropdown
fix average cinema rating to update with every review

Comment modal

---

app/models/comment.rb
app/models/vote.rb
app/views/notifications/_notification.html.erb
app/views/notifications/_notification_dot.html.erb
app/views/notifications/index.html.erb
app/views/shared/_bottom_navbar.html.erb

red dot appears in real time when a notification is present in the index page

add notification turbo stream, instant dot incomplete

---

app/controllers/favourites_controller.rb
app/javascript/controllers/favourite_controller.js
app/views/cinemas/show.html.erb
app/views/favourites/_favourite_list.html.erb
app/views/favourites/_toggle_button.html.erb
app/views/favourites/create.turbo_stream.erb
app/views/favourites/destroy.turbo_stream.erb

turbo stream toggle to the cinema show page to add/remove a cinema from favourites
turbo stream to remove a cinema from the favourites index page

Toggle favourites

---

app/controllers/pages_controller.rb
app/javascript/controllers/map_controller.js
app/models/cinema.rb
db/seeds.rb

remove duplicate 'geocoded_by' in cinema model
address correction for Everyman Barnet
custom styling for map

correct seeding problem

---

app/assets/stylesheets/pages/_favourites.scss

prevent overlap with delete button

fix name width

---

app/assets/stylesheets/components/_review_card.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/cinemas_controller.rb
app/controllers/pages_controller.rb
app/views/cinemas/_review.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/favourites/_toggle_button.html.erb
app/views/notifications/_notification_dot.html.erb
app/views/pages/home.html.erb
app/views/shared/_bottom_navbar.html.erb

Problem:
To use the app users needed to sign in/up first - poor UX if a user is just browsing the app.
Solution:
Allowed visitors to browse reviews and cinemas on the home and search pages without needing to make an account.
Users need an account to:
- Leave a review
- Vote/comment on a review
- Navigate to the favourites, notifications or profile pages
Also added a link back to the home page from the authentication pages

Authentication fix

---

app/assets/stylesheets/components/_review_card.scss
app/views/cinemas/_review.html.erb
app/views/comments/_comment.html.erb
app/views/notifications/_notification_dot.html.erb

Problem: warden error when a user voted/commented on another user's review, related to the use of user_signed_in? in the notification do partial
Solution: replace user_signed_in? with user .present? to fix
also noticed comment turbo stream formatting was altered by adding sign in link formatting to the review partial so also amended this

fix vote/comment auth issue

---

app/assets/stylesheets/pages/_map.scss
app/assets/stylesheets/pages/_show.scss
app/controllers/cinemas_controller.rb
app/views/cinemas/show.html.erb

allows user to filter review on show page newest-oldest, rating high-low (vice versa)
added turbo frames so page doesn't need to reload when a filter is changed

add review filters to show page

---

app/assets/stylesheets/pages/_profile.scss
db/seeds.rb

aligned review ratings with review content
improved general structure
tweak to profile page spacing

improve seed file
